export const ANCIENTS: IAncient[] = [
  {
    name: ANCIENT.ABHOTH,
    difficulty: 0,
    startingDoom: 14,
    mythosDeckSize: 16,
    expansion: EXPANSION.UNDER_THE_PYRAMIDS
  }, {
    name: ANCIENT.ANTEDILUVIUM,
    difficulty: 1,
    startingDoom: 13,
    mythosDeckSize: 16,
    expansion: EXPANSION.MASKS_OF_NYARLATHOTEP
  }, {
    name: ANCIENT.ATLACH_NACHA,
    difficulty: 1,
    startingDoom: 9,
    mythosDeckSize: 16,
    expansion: EXPANSION.THE_DREAMLANDS
  }, {
    name: ANCIENT.AZATHOTH,
    difficulty: 1,
    startingDoom: 15,
    mythosDeckSize: 16,
    expansion: EXPANSION.CORE
  }, {
    name: ANCIENT.CTHULHU,
    difficulty: 3,
    startingDoom: 12,
    mythosDeckSize: 15,
    expansion: EXPANSION.CORE
  }, {
    name: ANCIENT.THE_ELDER_THINGS,
    difficulty: 0,
    startingDoom: 16,
    mythosDeckSize: 20,
    expansion: EXPANSION.MOUNTAINS_OF_MADNESS
  }, {
    name: ANCIENT.HASTUR,
    difficulty: 3,
    startingDoom: 11,
    mythosDeckSize: 17,
    expansion: EXPANSION.SIGNS_OF_CARCOSA
  }, {
    name: ANCIENT.HYPNOS,
    difficulty: 0,
    startingDoom: 12,
    mythosDeckSize: 16,
    expansion: EXPANSION.THE_DREAMLANDS
  }, {
    name: ANCIENT.ITHAQUA,
    difficulty: 1,
    startingDoom: 13,
    mythosDeckSize: 16,
    expansion: EXPANSION.MOUNTAINS_OF_MADNESS
  }, {
    name: ANCIENT.NEPHREN_KA,
    difficulty: 1,
    startingDoom: 12,
    mythosDeckSize: 15,
    expansion: EXPANSION.UNDER_THE_PYRAMIDS
  }, {
    name: ANCIENT.NYARLATHOTEP,
    difficulty: 1,
    startingDoom: 12,
    mythosDeckSize: 16,
    expansion: EXPANSION.MASKS_OF_NYARLATHOTEP
  }, {
    name: ANCIENT.SHUB_NIGGURATH,
    difficulty: 1,
    startingDoom: 13,
    mythosDeckSize: 16,
    expansion: EXPANSION.CORE
  }, {
    name: ANCIENT.SHUDDE_M_ELL,
    difficulty: 3,
    startingDoom: 15,
    mythosDeckSize: 16,
    expansion: EXPANSION.CITIES_IN_RUIN
  }, {
    name: ANCIENT.SYZYGY,
    difficulty: 3,
    startingDoom: 13,
    mythosDeckSize: 18,
    expansion: EXPANSION.STRANGE_REMNANTS
  }, {
    name: ANCIENT.YIG,
    difficulty: 3,
    startingDoom: 10,
    mythosDeckSize: 16,
    expansion: EXPANSION.FORSAKEN_LORE
  }, {
    name: ANCIENT.YOG_SOTHOTH,
    difficulty: 0,
    startingDoom: 14,
    mythosDeckSize: 16,
    expansion: EXPANSION.CORE
  }
] as const
