export const EXPANSIONS: IExpansion[] = [
  {
    name: EXPANSION.CITIES_IN_RUIN,
    ancinets: [
      ANCIENT.SHUDDE_M_ELL
    ],
    preludes: [
      PRELUDE.APOCALYPSE_NIGH,
      PRELUDE.FALL_OF_MAN,
      PRELUDE.THE_PRICE_OF_PRESTIGE,
      PRELUDE.YOU_KNOW_WHAT_YOU_MUST_DO
    ]
  }, {
    name: EXPANSION.CORE,
    ancinets: [
      ANCIENT.AZATHOTH,
      ANCIENT.CTHULHU,
      ANCIENT.SHUB_NIGGURATH,
      ANCIENT.YOG_SOTHOTH
    ],
    preludes: []
  }, {
    name: EXPANSION.FORSAKEN_LORE,
    ancinets: [
      ANCIENT.YIG
    ],
    preludes: []
  }, {
    name: EXPANSION.MASKS_OF_NYARLATHOTEP,
    ancinets: [
      ANCIENT.ANTEDILUVIUM,
      ANCIENT.NYARLATHOTEP
    ],
    preludes: [
      PRELUDE.AID_OF_THE_ELDER_GODS,
      PRELUDE.THE_ARCHIVES,
      PRELUDE.ARMY_OF_DARKNESS,
      PRELUDE.FATHER_OF_SERPENTS,
      PRELUDE.HARBINGER_OF_THE_OUTER_GODS,
      PRELUDE.IN_THE_LIGHTLESS_CHAMBER,
      PRELUDE.THE_STARS_ALIGN,
      PRELUDE.TEMPTATION,
      PRELUDE.UNTO_THE_BREACH,
      PRELUDE.WONDROUS_CURIOS
    ]
  }, {
    name: EXPANSION.MOUNTAINS_OF_MADNESS,
    ancinets: [
      ANCIENT.THE_ELDER_THINGS,
      ANCIENT.ITHAQUA
    ],
    preludes: [
      PRELUDE.BEGINNING_OF_THE_END,
      PRELUDE.DOOMSAYER_FROM_ANTARCTICA,
      PRELUDE.KEY_TO_SALVATION,
      PRELUDE.RUMORS_FROM_THE_NORTH,
      PRELUDE.ULTIMATE_SACRIFICE,
      PRELUDE.UNWILLING_SACRIFICE
    ]
  }, {
    name: EXPANSION.SIGNS_OF_CARCOSA,
    ancinets: [
      ANCIENT.HASTUR
    ],
    preludes: [
      PRELUDE.THE_KING_IN_YELLOW,
      PRELUDE.SILVER_TWILIGHT_STOCKPILE,
      PRELUDE.SINS_OF_THE_PAST,
      PRELUDE.WEAKNESS_TO_STRENGTH
    ]
  }, {
    name: EXPANSION.STRANGE_REMNANTS,
    ancinets: [
      ANCIENT.SYZYGY
    ],
    preludes: [
      PRELUDE.DARK_BLESSINGS,
      PRELUDE.IN_COSMIC_ALIGNMENT,
      PRELUDE.THE_COMING_STORM,
      PRELUDE.THE_DUNWICH_HORROR
    ]
  }, {
    name: EXPANSION.THE_DREAMLANDS,
    ancinets: [
      ANCIENT.ATLACH_NACHA,
      ANCIENT.HYPNOS
    ],
    preludes: [
      PRELUDE.WRITTEN_IN_THE_STARS,
      PRELUDE.LURKER_AMONG_US,
      PRELUDE.TWIN_BLASPHEMIES_OF_THE_BLACK_GOAT,
      PRELUDE.WEB_BETWEEN_WORLDS,
      PRELUDE.OTHERWORLDLY_DREAMS,
      PRELUDE.FOCUSED_TRAINING
    ]
  }, {
    name: EXPANSION.UNDER_THE_PYRAMIDS,
    ancinets: [
      ANCIENT.ABHOTH,
      ANCIENT.NEPHREN_KA
    ],
    preludes: [
      PRELUDE.CALL_OF_CTHULHU,
      PRELUDE.DRASTIC_MEASURES,
      PRELUDE.EPIDEMIC,
      PRELUDE.GHOST_FROM_THE_PAST,
      PRELUDE.LITANY_OF_SECRETS,
      PRELUDE.UNDER_THE_PYRAMIDS
    ]
  }
]
