export const ANCIENT = {
  ABHOTH: "Abhoth",
  ANTEDILUVIUM: "Antediluvium",
  ATLACH_NACHA: "Atlach-Nacha",
  AZATHOTH: "Azathoth",
  CTHULHU: "Cthulhu",
  HASTUR: "Hastur",
  HYPNOS: "Hypnos",
  ITHAQUA: "Ithaqua",
  NEPHREN_KA: "Nephren-Ka",
  NYARLATHOTEP: "Nyarlathotep",
  SHUB_NIGGURATH: "Shub-Niggurath",
  SHUDDE_M_ELL: "Shudde M'ell",
  SYZYGY: "Syzygy",
  THE_ELDER_THINGS: "Rise of the Elder Things",
  YIG: "Yig",
  YOG_SOTHOTH: "Yog-Sothoth",
} as const

export const EXPANSION = {
  CITIES_IN_RUIN: "Cities in Ruin",
  CORE: "Core",
  FORSAKEN_LORE: "Forsaken Lore",
  MASKS_OF_NYARLATHOTEP: "Masks of Nyarlathotep",
  MOUNTAINS_OF_MADNESS: "Mountains of Madness",
  SIGNS_OF_CARCOSA: "Signs of Carcosa",
  STRANGE_REMNANTS: "Strange Remnants",
  THE_DREAMLANDS: "The Dreamlands",
  UNDER_THE_PYRAMIDS: "Under the Pyramids",
} as const

export const PRELUDE = {
  NONE: "None",
  BEGINNING_OF_THE_END: "Beginning of the End",
  DOOMSAYER_FROM_ANTARCTICA: "Doomsayer from Antarctica",
  KEY_TO_SALVATION: "Key to Salvation",
  RUMORS_FROM_THE_NORTH: "Rumors from the North",
  ULTIMATE_SACRIFICE: "Ultimate Sacrifice",
  UNWILLING_SACRIFICE: "Unwilling Sacrifice",
  DARK_BLESSINGS: "Dark Blessings",
  IN_COSMIC_ALIGNMENT: "In Cosmic Alignment",
  THE_COMING_STORM: "The Coming Storm",
  THE_DUNWICH_HORROR: "The Dunwich Horror",
  CALL_OF_CTHULHU: "Call of Cthulhu",
  DRASTIC_MEASURES: "Drastic Measures",
  EPIDEMIC: "Epidemic",
  GHOST_FROM_THE_PAST: "Ghost from the Past",
  LITANY_OF_SECRETS: "Litany of Secrets",
  UNDER_THE_PYRAMIDS: "Under the Pyramids",
  THE_KING_IN_YELLOW: "The King in Yellow",
  SILVER_TWILIGHT_STOCKPILE: "Silver Twilight Stockpile",
  SINS_OF_THE_PAST: "Sins of the Past",
  WEAKNESS_TO_STRENGTH: "Weakness to Strength",
  WRITTEN_IN_THE_STARS: "Written in the Stars",
  LURKER_AMONG_US: "Lurker Among Us",
  TWIN_BLASPHEMIES_OF_THE_BLACK_GOAT: "Twin Blasphemies of the Black Goat",
  WEB_BETWEEN_WORLDS: "Web Between Worlds",
  OTHERWORLDLY_DREAMS: "Otherworldly Dreams",
  FOCUSED_TRAINING: "Focused Training",
  APOCALYPSE_NIGH: "Apocalypse Nigh",
  FALL_OF_MAN: "Fall of Man",
  THE_PRICE_OF_PRESTIGE: "The Price of Prestige",
  YOU_KNOW_WHAT_YOU_MUST_DO: "You Know What You Must Do",
  AID_OF_THE_ELDER_GODS: "Aid of the Elder Gods",
  THE_ARCHIVES: "The Archives",
  ARMY_OF_DARKNESS: "Army of Darkness",
  FATHER_OF_SERPENTS: "Father of Serpents",
  HARBINGER_OF_THE_OUTER_GODS: "Harbinger of the Outer Gods",
  IN_THE_LIGHTLESS_CHAMBER: "In the Lightless Chamber",
  THE_STARS_ALIGN: "The Stars Align",
  TEMPTATION: "Temptation",
  UNTO_THE_BREACH: "Unto the Breach",
  WONDROUS_CURIOS: "Wondrous Curios",
} as const

export const INVESTIGATOR = {
  AGATHA_CRANE: "Agatha Crane",
  AGNES_BAKER: "Agnes Baker",
  AKACHI_ONYELE: "Akachi Onyele",
  AMANDA_SHARPE: "Amanda Sharpe",
  ASHCAN_PETE: "\"Ashcan\" Pete",
  BOB_JENKINS: "Bob Jenkins",
  CALVIN_WRIGHT: "Calvin Wright",
  CAROLYN_FERN: "Carolyn Fern",
  CARSON_SINCLAIR: "Carson Sinclair",
  CHARLIE_KANE: "Charlie Kane",
  DAISY_WALKER: "Daisy Walker",
  DANIELA_REYES: "Daniela Reyes",
  DARRELL_SIMMONS: "Darrell Simmons",
  DEXTER_DRAKE: "Dexter Drake",
  DIANA_STANLEY: "Diana Stanley",
  FATHER_MATEO: "Father Mateo",
  FINN_EDWARDS: "Finn Edwards",
  GEORGE_BARNABY: "George Barnaby",
  GLORIA_GOLDBERG: "Gloria Goldberg",
  HANK_SAMSON: "Hank Samson",
  HARVEY_WALTERS: "Harvey Walters",
  JACQUELINE_FINE: "Jacqueline Fine",
  JENNY_BARNES: "Jenny Barnes",
  JIM_CULVER: "Jim Culver",
  JOE_DIAMOND: "Joe Diamond",
  KATE_WINTHROP: "Kate Winthrop",
  LEO_ANDERSON: "Leo Anderson",
  LILY_CHEN: "Lily Chen",
  LOLA_HAYES: "Lola Hayes",
  LUKE_ROBINSON: "Luke Robinson",
  MANDY_THOMPSON: "Mandy Thompson",
  MARIE_LAMBEAU: "Marie Lambeau",
  MARK_HARRIGAN: "Mark Harrigan",
  MICHAEL_MC_GLEN: "Michael McGlen",
  MINH_THI_PHAN: "Minh Thi Phan",
  MONTEREY_JACK: "Monterey Jack",
  NORMAN_WITHERS: "Norman Withers",
  PATRICE_HATHAWAY: "Patrice Hathaway",
  PRESTON_FAIRMONT: "Preston Fairmont",
  REX_MURPHY: "Rex Murphy",
  RITA_YOUNG: "Rita Young",
  ROLAND_BANKS: "Roland Banks",
  SEFINA_ROUSSEAU: "Sefina Rousseau",
  SILAS_MARSH: "Silas Marsh",
  SISTER_MARY: "Sister Mary",
  SKIDS_O_TOOLE: "\"Skids\" O'Toole",
  TOMMY_MULDOON: "Tommy Muldoon",
  TONY_MORGAN: "Tony Morgan",
  TRISH_SCARBOROUGH: "Trish Scarborough",
  URSULA_DOWNS: "Ursula Downs",
  VINCENT_LEE: "Vincent Lee",
  WENDY_ADAMS: "Wendy Adams",
  WILLIAM_YORICK: "William Yorick",
  WILSON_RICHARDS: "Wilson Richards",
  ZOEY_SAMARAS: "Zoey Samaras"
} as const

export const SCORE = {
  GATES: "Number of open Gates on the game board",
  MONSTERS: "Number of Monsters on the game board",
  CURSED: "Total number of \"Cursed\" or \"Dark Pact\" Conditions",
  RUMORS: "Number of Rumor Mythos card in play",
  CLUES: "Total number of Clue tokens investigators have",
  BLESSED: "Total number of \"Blessed\" Conditions investigators have",
  DOOM: "Current level of Doom"
} as const

export const REASON = {
  SURRENDER: "Surrender",
  ELIMINATED: "All investigators have been eliminated",
  OUT_OF_MYTHOS_CARD: "A Mythos card cannot be drawn",
  ANCIENT_ONE_SHEET: "Indication on the Ancient One sheet",
  RUMOR_CARD: "Indication on the Rumor card",
  PRELUDE_CARD: "Indication on the Prelude card"
} as const

export const ANCIENT_NAMES = Object.values(ANCIENT)
export const INVESTIGATOR_NAMES = Object.values(INVESTIGATOR)
export const INVESTIGATOR_TEAMS: InvestigatorTeam[] = ['initial', 'replacement']
export const MYTH_TYPES: IGameMythos[] = ['easy', 'normal', 'hard']
export const PRELUDE_NAMES = Object.values(PRELUDE)
export const REASON_NAMES = Object.values(REASON)
