export const ANCIENT = {
  ABHOTH: "Abhoth",
  ANTEDILUVIUM: "Antediluvium",
  ATLACH_NACHA: "Atlach-Nacha",
  AZATHOTH: "Azathoth",
  CTHULHU: "Cthulhu",
  HASTUR: "Hastur",
  HYPNOS: "Hypnos",
  ITHAQUA: "Ithaqua",
  NEPHREN_KA: "Nephren-Ka",
  NYARLATHOTEP: "Nyarlathotep",
  SHUB_NIGGURATH: "Shub-Niggurath",
  SHUDDE_M_ELL: "Shudde M'ell",
  SYZYGY: "Syzygy",
  THE_ELDER_THINGS: "Rise of the Elder Things",
  YIG: "Yig",
  YOG_SOTHOTH: "Yog-Sothoth",
} as const

export const EXPANSION = {
  CITIES_IN_RUIN: "Cities in Ruin",
  CORE: "Core",
  FORSAKEN_LORE: "Forsaken Lore",
  MASKS_OF_NYARLATHOTEP: "Masks of Nyarlathotep",
  MOUNTAINS_OF_MADNESS: "Mountains of Madness",
  SIGNS_OF_CARCOSA: "Signs of Carcosa",
  STRANGE_REMNANTS: "Strange Remnants",
  THE_DREAMLANDS: "The Dreamlands",
  UNDER_THE_PYRAMIDS: "Under the Pyramids",
} as const

export const PRELUDE = {
  BEGINNING_OF_THE_END: "Beginning of the End",
  DOOMSAYER_FROM_ANTARCTICA: "Doomsayer from Antarctica",
  KEY_TO_SALVATION: "Key to Salvation",
  RUMORS_FROM_THE_NORTH: "Rumors from the North",
  ULTIMATE_SACRIFICE: "Ultimate Sacrifice",
  UNWILLING_SACRIFICE: "Unwilling Sacrifice",
  DARK_BLESSINGS: "Dark Blessings",
  IN_COSMIC_ALIGNMENT: "In Cosmic Alignment",
  THE_COMING_STORM: "The Coming Storm",
  THE_DUNWICH_HORROR: "The Dunwich Horror",
  CALL_OF_CTHULHU: "Call of Cthulhu",
  DRASTIC_MEASURES: "Drastic Measures",
  EPIDEMIC: "Epidemic",
  GHOST_FROM_THE_PAST: "Ghost from the Past",
  LITANY_OF_SECRETS: "Litany of Secrets",
  UNDER_THE_PYRAMIDS: "Under the Pyramids",
  THE_KING_IN_YELLOW: "The King in Yellow",
  SILVER_TWILIGHT_STOCKPILE: "Silver Twilight Stockpile",
  SINS_OF_THE_PAST: "Sins of the Past",
  WEAKNESS_TO_STRENGTH: "Weakness to Strength",
  WRITTEN_IN_THE_STARS: "Written in the Stars",
  LURKER_AMONG_US: "Lurker Among Us",
  TWIN_BLASPHEMIES_OF_THE_BLACK_GOAT: "Twin Blasphemies of the Black Goat",
  WEB_BETWEEN_WORLDS: "Web Between Worlds",
  OTHERWORLDLY_DREAMS: "Otherworldly Dreams",
  FOCUSED_TRAINING: "Focused Training",
  APOCALYPSE_NIGH: "Apocalypse Nigh",
  FALL_OF_MAN: "Fall of Man",
  THE_PRICE_OF_PRESTIGE: "The Price of Prestige",
  YOU_KNOW_WHAT_YOU_MUST_DO: "You Know What You Must Do",
  AID_OF_THE_ELDER_GODS: "Aid of the Elder Gods",
  THE_ARCHIVES: "The Archives",
  ARMY_OF_DARKNESS: "Army of Darkness",
  FATHER_OF_SERPENTS: "Father of Serpents",
  HARBINGER_OF_THE_OUTER_GODS: "Harbinger of the Outer Gods",
  IN_THE_LIGHTLESS_CHAMBER: "In the Lightless Chamber",
  THE_STARS_ALIGN: "The Stars Align",
  TEMPTATION: "Temptation",
  UNTO_THE_BREACH: "Unto the Breach",
  WONDROUS_CURIOS: "Wondrous Curios",
} as const

export const SCORE = {
  GATES: "Number of open Gates on the game board",
  MONSTERS: "Number of Monsters on the game board",
  CURSED: "Total number of \"Cursed\" or \"Dark Pact\" Conditions",
  RUMORS: "Number of Rumor Mythos card in play",
  CLUES: "Total number of Clue tokens investigators have",
  BLESSED: "Total number of \"Blessed\" Conditions investigators have",
  DOOM: "Current level of Doom"
} as const

export const REASON = {
  SURRENDER: "Surrender",
  ELIMINATED: "All investigators have been eliminated",
  OUT_OF_MYTHOS_CARD: "A Mythos card cannot be drawn",
  ANCIENT_ONE_SHEET: "Indication on the Ancient One sheet",
  RUMOR_CARD: "Indication on the Rumor card",
  PRELUDE_CARD: "Indication on the Prelude card"
} as const
